name: demo_ai_even
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  get: ^4.6.6
  crclib: ^3.0.0
  fluttertoast: ^8.2.8
  flutter_blue_plus: ^1.31.15   # ✅ Bluetooth support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf