name: APK Release

on:
  workflow_run:
    workflows: ["Flutter CI (Build Debug + Release)"]
    types: [completed]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish GitHub Release with APKs
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-build
          name: "Latest Build"
          body: |
            🚀 Automated build from commit ${{ github.event.workflow_run.head_sha }}

            - Commit: [${{ github.event.workflow_run.head_sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.workflow_run.head_sha }})
            - Triggered by: ${{ github.actor }}
          draft: false
          prerelease: false
          files: |
            artifacts/app-release/app-release.apk
            artifacts/app-debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}