name: CI Failure Reporting

on:
  workflow_run:
    workflows: ["Flutter CI (Build Debug + Release)"]
    types: [completed]

permissions:
  issues: write
  contents: read

jobs:
  report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-logs
          path: ./logs

      - name: Prepare Issue Body
        run: |
          FULL_LOG=$(cat ./logs/debug-build-log.txt ./logs/release-build-log.txt || echo "⚠️ Empty log")
          KEY_ERRORS=$(echo "$FULL_LOG" | grep -i "error\|exception\|failed\|fatal" | tail -40 || echo "⚠️ No explicit error logs")

          cat > issue-body.md << EOF
          # 🚨 CI Build Failure Report
          Workflow: [Flutter CI Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }})

          ## ❌ Key Errors
          \`\`\`
          ${KEY_ERRORS}
          \`\`\`

          ## 📋 Last 200 Lines
          \`\`\`
          $(echo "$FULL_LOG" | tail -200)
          \`\`\`

          ---
          *This issue was auto-generated by GitHub Actions.*
          EOF

      - uses: peter-evans/create-issue-from-file@v5
        with:
          title: "🚨 CI Build Failure - ${{ github.ref_name }}"
          content-filepath: issue-body.md
          labels: |
            bug
            ci-failure
            auto-generated

  autoclose:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'ci-failure,auto-generated'
            });
            for (const issue of issues.data) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed',
                body: issue.body + "\n\n✅ CI build passed. Auto-closing this issue."
              });
            }