name: Flutter CI (Debug + Release with Issues + Release)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          cache: true

      - name: Install dependencies
        run: flutter pub get --no-precompile

      # Debug build
      - name: Build Debug APK
        run: flutter build apk --debug 2>&1 | tee debug-build-log.txt

      # Release build
      - name: Build Release APK
        run: flutter build apk --release 2>&1 | tee release-build-log.txt

      # 🔍 Confirm APK paths
      - name: List generated APKs
        run: |
          echo "📂 Checking APK output directories..."
          ls -lh build/app/outputs/ || echo "⚠️ outputs/ missing"
          ls -lh build/app/outputs/flutter-apk/ || echo "⚠️ flutter-apk/ missing"
          ls -lh build/app/outputs/apk/ || echo "⚠️ apk/ missing"

      # ✅ Upload Debug APK (check both possible paths)
      - name: Upload Debug Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/apk/debug/app-debug.apk
          retention-days: 30
          if-no-files-found: warn

      # ✅ Upload Release APK (check both possible paths)
      - name: Upload Release Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/apk/release/app-release.apk
          retention-days: 30
          if-no-files-found: warn

      # ✅ Upload Logs (always, for debugging)
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            debug-build-log.txt
            release-build-log.txt
          retention-days: 30

      # ✅ Create issue if build fails (with logs)
      - name: Create formatted issue body
        if: failure()
        run: |
          KEY_ERRORS=$(grep -i "error\|exception\|failed\|fatal" debug-build-log.txt release-build-log.txt | tail -40 || echo "⚠️ No explicit error logs")
          FULL_LOG=$(tail -n 200 debug-build-log.txt release-build-log.txt || echo "⚠️ Logs empty")

          cat > issue-body.md << EOF
          # 🚨 CI Build Failure Report
          **Branch:** ${{ github.ref_name }}
          **Commit:** [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          **Workflow Run:** [View Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          ## ❌ Key Errors (last 40 lines)
          \`\`\`
          ${KEY_ERRORS}
          \`\`\`

          ## 📋 Log Snippet (last 200 lines)
          <details><summary>Expand</summary>

          \`\`\`
          ${FULL_LOG}
          \`\`\`

          </details>

          ---
          *This issue was auto-generated by GitHub Actions.*
          EOF

      - name: Create GitHub Issue with logs
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "🚨 CI Build Failure - ${{ github.ref_name }}"
          content-filepath: issue-body.md
          labels: |
            bug
            ci-failure
            auto-generated

      # ✅ Publish/update "Latest Build" release with APKs (only on success)
      - name: Create or Update GitHub Release with APKs
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-build
          name: "Latest Build"
          body: |
            🚀 Automated build from commit ${{ github.sha }}

            - Commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            - Triggered by: ${{ github.actor }}
          draft: false
          prerelease: false
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/apk/release/app-release.apk
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Auto-close CI failure issues if this build succeeds
      - name: Auto-close resolved CI failure issues
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'ci-failure,auto-generated'
            });
            for (const issue of issues.data) {
              if (issue.title.includes(process.env.GITHUB_REF_NAME)) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed',
                  body: issue.body + "\n\n✅ CI build passed. Auto-closing this issue."
                });
              }
            }