name: Flutter CI (Debug + Release with Smart Issues + Cache)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK (Debug)
        id: build_debug
        run: |
          set -o pipefail
          echo "🔨 Building debug APK..."
          flutter build apk --debug 2>&1 | tee build-debug-log.txt
          echo "debug_exit_code=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT

      - name: Build Android APK (Release)
        id: build_release
        run: |
          set -o pipefail
          echo "🔨 Building release APK..."
          flutter build apk --release 2>&1 | tee build-release-log.txt
          echo "release_exit_code=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT

      - name: Create formatted issue body on failure
        if: failure()
        run: |
          cat > issue-body.md << 'EOF'
          # 🚨 CI Build Failure Report

          **Branch:** `${{ github.ref_name }}`
          **Commit:** [`${{ github.sha }}`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          **Triggered by:** ${{ github.actor }}
          **Workflow Run:** [View Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          ## 🔍 Debug Build Log (last 20 lines)
          ```
          $(tail -20 build-debug-log.txt)
          ```

          ## 🔍 Release Build Log (last 20 lines)
          ```
          $(tail -20 build-release-log.txt)
          ```

          ## 🛠️ Troubleshooting Checklist
          - [ ] Check dependency compatibility
          - [ ] Verify Flutter/Dart SDK versions
          - [ ] Review recent code changes
          - [ ] Validate Gradle/Android setup
          - [ ] Retry with `flutter clean && flutter pub get`

          ---
          *This issue was auto-generated by CI. It will auto-close when the same commit/branch passes.*
          EOF

      - name: Create GitHub Issue with formatted content
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "🚨 CI Build Failure - ${{ github.ref_name }} (${{ github.sha }})"
          content-filepath: issue-body.md
          labels: |
            bug
            ci-failure
            auto-generated
            ${{ github.ref_name }}
          assignees: ${{ github.actor }}

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-failure-artifacts-${{ github.sha }}
          path: |
            build-debug-log.txt
            build-release-log.txt
            issue-body.md
          retention-days: 7

      # ✅ Auto-close resolved issues ONLY when this commit/branch passes
      - name: Auto-close resolved CI failure issues
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'ci-failure,auto-generated'
            });

            for (const issue of issues.data) {
              if (issue.title.includes(process.env.GITHUB_REF_NAME) ||
                  issue.title.includes(process.env.GITHUB_SHA)) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed',
                  body: "✅ CI build has passed for this branch/commit. Closing issue automatically."
                });
                console.log(`Closed resolved CI issue #${issue.number}`);
              }
            }