name: Flutter CI (Build Debug + Release)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          cache: true
      - run: flutter pub get --no-precompile

      - name: Build Debug APK
        run: flutter build apk --debug 2>&1 | tee debug-build-log.txt

      - name: Build Release APK
        run: flutter build apk --release 2>&1 | tee release-build-log.txt

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            debug-build-log.txt
            release-build-log.txt
          retention-days: 30