# .github/workflows/flutter-ci.yml
name: Flutter CI (Build Debug + Release)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          cache: true
      - run: flutter pub get --no-precompile

      - name: Build Debug APK
        run: flutter build apk --debug 2>&1 | tee debug-build-log.txt

      - name: Build Release APK
        run: flutter build apk --release 2>&1 | tee release-build-log.txt

      # 🔍 Debugging step to confirm APK output
      - name: List generated APKs
        run: ls -R build/app/outputs/ || echo "⚠️ No APK outputs found"

      # ✅ Upload Debug APK
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 30
          if-no-files-found: warn

      # ✅ Upload Release APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
          if-no-files-found: warn

      # ✅ Upload Build Logs
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            debug-build-log.txt
            release-build-log.txt
          retention-days: 30

      # ✅ Upload BLE Debug Log (from device log file if available)
      - name: Upload BLE Debug Log
        uses: actions/upload-artifact@v4
        with:
          name: ble-debug-log
          path: |
            /storage/emulated/0/Download/ble_debug_log.txt
            build/app/outputs/ble_debug_log.txt
          retention-days: 30
          if-no-files-found: ignore