name: Flutter CI with Auto-Issue Export

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout source
        uses: actions/checkout@v4

      # Setup Java (required for Android builds)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.3   # ✅ use your Flutter version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run build
      - name: Build APK
        run: flutter build apk --release
        continue-on-error: true

      # Upload build artifacts (for debugging/download)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build
          path: build/app/outputs/flutter-apk/

      # Upload logs for troubleshooting
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build/

  export-issue:
    needs: build
    runs-on: ubuntu-latest
    if: failure()

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Download logs from previous job
      - name: Download build logs
        uses: actions/download-artifact@v4
        with:
          name: build-logs
          path: ./logs

      # Create a GitHub issue if build fails
      - name: Create issue on failure
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Flutter CI Build Failed 🚨"
          content-filepath: ./logs/flutter_01.log
          labels: |
            bug
            CI