name: Flutter CI (Android Debug + Release Builds with Smart Issue Reporting)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # ------------------------
      # Checkout & Setup
      # ------------------------
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      # ------------------------
      # Release Build
      # ------------------------
      - name: Build Android APK (Release)
        id: build-release
        run: |
          set -o pipefail
          echo "🔨 Building Release APK..."
          flutter build apk --release 2>&1 | tee build-release-log.txt
          echo "build_exit_code=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT

      # ------------------------
      # Debug Build
      # ------------------------
      - name: Build Android APK (Debug)
        id: build-debug
        run: |
          set -o pipefail
          echo "🔨 Building Debug APK..."
          flutter build apk --debug 2>&1 | tee build-debug-log.txt
          echo "build_exit_code=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT

      # ------------------------
      # Upload APKs + Logs as Artifacts
      # ------------------------
      - name: Upload APKs and Logs
        uses: actions/upload-artifact@v4
        with:
          name: android-build-artifacts-${{ github.sha }}
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/app-debug.apk
            build-release-log.txt
            build-debug-log.txt
          retention-days: 14

      # ------------------------
      # Create GitHub Issue (on Release build failure only)
      # ------------------------
      - name: Export Release Build Failure to GitHub Issue
        if: failure() && steps.build-release.outcome == 'failure'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "🚨 Android Release Build Failure - ${{ github.ref_name }} (${{ github.sha }})"
          content-filepath: build-release-log.txt
          labels: |
            bug
            ci-failure
            android
          assignees: ${{ github.actor }}

      # ------------------------
      # Close auto-generated issue if build succeeds
      # ------------------------
      - name: Close CI Failure Issues
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'ci-failure,android'
            });

            for (const issue of issues.data) {
              if (issue.title.includes('Android Release Build Failure')) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed',
                  state_reason: 'completed'
                });
                console.log(`✅ Closed previous CI failure issue #${issue.number}`);
              }
            }