name: Flutter CI (Android Release Build with Auto-Issue Export)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK (Release)
        id: build
        run: |
          set -o pipefail
          echo "🔨 Starting Flutter release build..."
          flutter build apk --release 2>&1 | tee build-log.txt
          BUILD_EXIT_CODE=${PIPESTATUS[0]}
          echo "build_exit_code=$BUILD_EXIT_CODE" >> $GITHUB_OUTPUT
          echo "✅ Build step finished with exit code $BUILD_EXIT_CODE"
          exit $BUILD_EXIT_CODE

      # ✅ Extract version info from build.gradle for artifact naming
      - name: Extract version info
        id: version
        run: |
          VERSION_NAME=$(grep versionName android/app/build.gradle | awk '{print $2}' | tr -d '"')
          VERSION_CODE=$(grep versionCode android/app/build.gradle | awk '{print $2}')
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT

      # ✅ Upload APK on success, with versioned name
      - name: Upload release APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk-v${{ steps.version.outputs.version_name }}+${{ steps.version.outputs.version_code }}
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30

      # ⛔ Export logs on failure
      - name: Upload logs as artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build-log.txt

      - name: Export build failure to GitHub Issue
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "🚨 CI Build Failure"
          content-filepath: build-log.txt
          labels: |
            bug
            ci-failure
            auto-generated