name: Flutter CI (Release Build with Auto-Issue Export)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android Release APK
        id: build
        run: |
          set -o pipefail
          flutter build apk --release 2>&1 | tee build-log.txt

      - name: Upload logs as artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build-log.txt

      - name: Export build failure to GitHub Issue
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "CI Build Failure: Android Release"
          content-filepath: build-log.txt
          labels: bug, ci-failure
          assignees: loopermallee

      - name: Append environment details to issue
        if: failure()
        run: |
          {
            echo "### Environment Info"
            echo "- Flutter: $(flutter --version)"
            echo "- Java: $(java -version 2>&1 | head -n 1)"
            echo "- Gradle: $(./gradlew --version | head -n 3)"
            echo "- OS: $(uname -a)"
          } >> build-log.txt