      # 🔍 Debugging step to confirm APK paths
      - name: List generated APKs
        run: |
          echo "📂 Checking APK output directories..."
          ls -lh build/app/outputs/ || echo "⚠️ outputs/ missing"
          ls -lh build/app/outputs/flutter-apk/ || echo "⚠️ flutter-apk/ missing"
          ls -lh build/app/outputs/apk/ || echo "⚠️ apk/ missing"

      # ✅ Upload Debug APK (check both possible paths)
      - name: Upload Debug Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-universal
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/apk/debug/app-debug.apk
          retention-days: 30
          if-no-files-found: warn

      # ✅ Upload Release APK (check both possible paths)
      - name: Upload Release Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-universal
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/apk/release/app-release.apk
          retention-days: 30
          if-no-files-found: warn

      # ✅ Upload Logs
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            debug-build-log.txt
            release-build-log.txt
          retention-days: 30